apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-ca-issuer
  namespace: istio-system
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ca
  namespace: istio-system
spec:
  dnsNames:
    - reddtsai.org
  isCA: true
  duration: 2160h
  renewBefore: 360h
  commonName: argocd.reddtsai.org
  subject:
    organizations:
      - reddtsai
    organizationalUnits:
      - reddtsai.org
  secretName: argocd-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: argocd-ca-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "argocd.reddtsai.org"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "argocd.reddtsai.org"
      tls:
        credentialName: argocd-ca-secret
        mode: SIMPLE

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
    - "*"
  gateways:
    - argocd-gateway
  http:
    - route:
        - destination:
            host: argocd-server
            port:
              number: 80
