apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: istio-system
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  namespace: istio-system
spec:
  dnsNames:
    - reddtsai.org
  isCA: true
  duration: 2160h
  renewBefore: 360h
  commonName: www.reddtsai.org
  subject:
    organizations:
      - reddtsai
    organizationalUnits:
      - reddtsai.org
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
