apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: reddtsai-org-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: reddtsai-org-ca
spec:
  dnsNames:
    - reddtsai.org
  isCA: true
  duration: 2160h
  renewBefore: 360h
  commonName: reddtsai.org
  subject:
    organizations:
      - reddtsai
    organizationalUnits:
      - reddtsai.org
  secretName: reddtsai-org-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: reddtsai-org-issuer
    kind: Issuer
    group: cert-manager.io
